// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from "@prisma/orm-postgres/target/codec-types";
import type { QueryOperationTypes as PgTargetQueryOps } from "@prisma/orm-postgres/target/operation-types";

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from "@prisma/orm-postgres/family-contract/types";
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from "@prisma/orm-postgres/contract/types";

export type StorageHash =
  StorageHashBase<"fa81d9d20dbbe088f84245487a87a399a9471337835088b9f63025848ad4b4ae">;
export type ExecutionHash =
  ExecutionHashBase<"59fc6d04733e623c37c05908b88c3117a0c7e0ae53f640da99debbd52a2aefbd">;
export type ProfileHash =
  ProfileHashBase<"3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2">;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgTargetQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly "pg/float@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/float4@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/float8@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/int@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/int2@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/int4@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/int8@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/int8number@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/interval@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/numeric@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/time-string@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/time-temporal@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "sql/float@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "sql/int@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly "pg/int@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/int2@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/int4@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/int8@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/int8number@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/numeric@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "sql/int@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: {
      readonly output: "pg/int8number@1";
      readonly nullable: false;
    };
    readonly anyInput: {
      readonly output: "pg/int8number@1";
      readonly nullable: false;
    };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: {
      readonly output: "pg/int8@1";
      readonly nullable: false;
    };
    readonly anyInput: {
      readonly output: "pg/int8@1";
      readonly nullable: false;
    };
  };
  readonly max: {
    readonly byCodec: {
      readonly "pg/char@1": {
        readonly output: "pg/char@1";
        readonly nullable: true;
      };
      readonly "pg/date-string@1": {
        readonly output: "pg/date-string@1";
        readonly nullable: true;
      };
      readonly "pg/date-temporal@1": {
        readonly output: "pg/date-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/enum@1": {
        readonly output: "pg/enum@1";
        readonly nullable: true;
      };
      readonly "pg/float@1": {
        readonly output: "pg/float@1";
        readonly nullable: true;
      };
      readonly "pg/float4@1": {
        readonly output: "pg/float4@1";
        readonly nullable: true;
      };
      readonly "pg/float8@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/inet@1": {
        readonly output: "pg/inet@1";
        readonly nullable: true;
      };
      readonly "pg/int@1": {
        readonly output: "pg/int@1";
        readonly nullable: true;
      };
      readonly "pg/int2@1": {
        readonly output: "pg/int2@1";
        readonly nullable: true;
      };
      readonly "pg/int4@1": {
        readonly output: "pg/int4@1";
        readonly nullable: true;
      };
      readonly "pg/int8@1": {
        readonly output: "pg/int8@1";
        readonly nullable: true;
      };
      readonly "pg/int8number@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/interval@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/numeric@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/text-array@1": {
        readonly output: "pg/text-array@1";
        readonly nullable: true;
      };
      readonly "pg/text@1": {
        readonly output: "pg/text@1";
        readonly nullable: true;
      };
      readonly "pg/time-string@1": {
        readonly output: "pg/time-string@1";
        readonly nullable: true;
      };
      readonly "pg/time-temporal@1": {
        readonly output: "pg/time-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timestamp-string@1": {
        readonly output: "pg/timestamp-string@1";
        readonly nullable: true;
      };
      readonly "pg/timestamp-temporal@1": {
        readonly output: "pg/timestamp-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-date@1": {
        readonly output: "pg/timestamptz-date@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-string@1": {
        readonly output: "pg/timestamptz-string@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-temporal@1": {
        readonly output: "pg/timestamptz-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timetz@1": {
        readonly output: "pg/timetz@1";
        readonly nullable: true;
      };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "pg/varchar@1": {
        readonly output: "pg/text@1";
        readonly nullable: true;
      };
      readonly "sql/char@1": {
        readonly output: "sql/char@1";
        readonly nullable: true;
      };
      readonly "sql/float@1": {
        readonly output: "sql/float@1";
        readonly nullable: true;
      };
      readonly "sql/int@1": {
        readonly output: "sql/int@1";
        readonly nullable: true;
      };
      readonly "sql/text@1": {
        readonly output: "sql/text@1";
        readonly nullable: true;
      };
      readonly "sql/varchar@1": {
        readonly output: "pg/text@1";
        readonly nullable: true;
      };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly "pg/char@1": {
        readonly output: "pg/char@1";
        readonly nullable: true;
      };
      readonly "pg/date-string@1": {
        readonly output: "pg/date-string@1";
        readonly nullable: true;
      };
      readonly "pg/date-temporal@1": {
        readonly output: "pg/date-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/enum@1": {
        readonly output: "pg/enum@1";
        readonly nullable: true;
      };
      readonly "pg/float@1": {
        readonly output: "pg/float@1";
        readonly nullable: true;
      };
      readonly "pg/float4@1": {
        readonly output: "pg/float4@1";
        readonly nullable: true;
      };
      readonly "pg/float8@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/inet@1": {
        readonly output: "pg/inet@1";
        readonly nullable: true;
      };
      readonly "pg/int@1": {
        readonly output: "pg/int@1";
        readonly nullable: true;
      };
      readonly "pg/int2@1": {
        readonly output: "pg/int2@1";
        readonly nullable: true;
      };
      readonly "pg/int4@1": {
        readonly output: "pg/int4@1";
        readonly nullable: true;
      };
      readonly "pg/int8@1": {
        readonly output: "pg/int8@1";
        readonly nullable: true;
      };
      readonly "pg/int8number@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/interval@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/numeric@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/text-array@1": {
        readonly output: "pg/text-array@1";
        readonly nullable: true;
      };
      readonly "pg/text@1": {
        readonly output: "pg/text@1";
        readonly nullable: true;
      };
      readonly "pg/time-string@1": {
        readonly output: "pg/time-string@1";
        readonly nullable: true;
      };
      readonly "pg/time-temporal@1": {
        readonly output: "pg/time-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timestamp-string@1": {
        readonly output: "pg/timestamp-string@1";
        readonly nullable: true;
      };
      readonly "pg/timestamp-temporal@1": {
        readonly output: "pg/timestamp-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-date@1": {
        readonly output: "pg/timestamptz-date@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-string@1": {
        readonly output: "pg/timestamptz-string@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-temporal@1": {
        readonly output: "pg/timestamptz-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timetz@1": {
        readonly output: "pg/timetz@1";
        readonly nullable: true;
      };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "pg/varchar@1": {
        readonly output: "pg/text@1";
        readonly nullable: true;
      };
      readonly "sql/char@1": {
        readonly output: "sql/char@1";
        readonly nullable: true;
      };
      readonly "sql/float@1": {
        readonly output: "sql/float@1";
        readonly nullable: true;
      };
      readonly "sql/int@1": {
        readonly output: "sql/int@1";
        readonly nullable: true;
      };
      readonly "sql/text@1": {
        readonly output: "sql/text@1";
        readonly nullable: true;
      };
      readonly "sql/varchar@1": {
        readonly output: "pg/text@1";
        readonly nullable: true;
      };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly "pg/float@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/float4@1": {
        readonly output: "pg/float4@1";
        readonly nullable: true;
      };
      readonly "pg/float8@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/int@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/int2@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/int4@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/int8@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/int8number@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/interval@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/numeric@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/time-string@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/time-temporal@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "sql/float@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "sql/int@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly "pg/int@1": {
        readonly output: "pg/int8@1";
        readonly nullable: true;
      };
      readonly "pg/int2@1": {
        readonly output: "pg/int8@1";
        readonly nullable: true;
      };
      readonly "pg/int4@1": {
        readonly output: "pg/int8@1";
        readonly nullable: true;
      };
      readonly "pg/int8@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "pg/int8number@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "sql/int@1": {
        readonly output: "pg/int8@1";
        readonly nullable: true;
      };
    };
  };
};
type DefaultLiteralValue<
  CodecId extends string,
  Encoded,
> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]["json"]
    ? Encoded
    : CodecTypes[CodecId]["json"]
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Product: {
      readonly brand: CodecTypes["pg/text@1"]["output"];
      readonly category: CodecTypes["pg/text@1"]["output"];
      readonly color: CodecTypes["pg/text@1"]["output"] | null;
      readonly featured: CodecTypes["pg/bool@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly name: CodecTypes["pg/text@1"]["output"];
      readonly price: CodecTypes["pg/float8@1"]["output"];
      readonly processor: CodecTypes["pg/text@1"]["output"] | null;
      readonly ram: CodecTypes["pg/int4@1"]["output"] | null;
      readonly rating: CodecTypes["pg/float8@1"]["output"];
      readonly releaseYear: CodecTypes["pg/int4@1"]["output"];
      readonly status: CodecTypes["pg/text@1"]["output"];
      readonly stock: CodecTypes["pg/int4@1"]["output"];
      readonly storage: CodecTypes["pg/int4@1"]["output"] | null;
    };
    readonly User: {
      readonly avatar: CodecTypes["pg/text@1"]["output"] | null;
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly email: CodecTypes["pg/text@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly name: CodecTypes["pg/text@1"]["output"] | null;
      readonly otpExpiry:
        CodecTypes["pg/timestamptz-string@1"]["output"] | null;
      readonly password: CodecTypes["pg/text@1"]["output"] | null;
      readonly refreshToken: CodecTypes["pg/text@1"]["output"] | null;
      readonly resetOtp: CodecTypes["pg/text@1"]["output"] | null;
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly username: CodecTypes["pg/text@1"]["output"] | null;
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Product: {
      readonly brand: CodecTypes["pg/text@1"]["input"];
      readonly category: CodecTypes["pg/text@1"]["input"];
      readonly color: CodecTypes["pg/text@1"]["input"] | null;
      readonly featured: CodecTypes["pg/bool@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly name: CodecTypes["pg/text@1"]["input"];
      readonly price: CodecTypes["pg/float8@1"]["input"];
      readonly processor: CodecTypes["pg/text@1"]["input"] | null;
      readonly ram: CodecTypes["pg/int4@1"]["input"] | null;
      readonly rating: CodecTypes["pg/float8@1"]["input"];
      readonly releaseYear: CodecTypes["pg/int4@1"]["input"];
      readonly status: CodecTypes["pg/text@1"]["input"];
      readonly stock: CodecTypes["pg/int4@1"]["input"];
      readonly storage: CodecTypes["pg/int4@1"]["input"] | null;
    };
    readonly User: {
      readonly avatar: CodecTypes["pg/text@1"]["input"] | null;
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly email: CodecTypes["pg/text@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly name: CodecTypes["pg/text@1"]["input"] | null;
      readonly otpExpiry: CodecTypes["pg/timestamptz-string@1"]["input"] | null;
      readonly password: CodecTypes["pg/text@1"]["input"] | null;
      readonly refreshToken: CodecTypes["pg/text@1"]["input"] | null;
      readonly resetOtp: CodecTypes["pg/text@1"]["input"] | null;
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly username: CodecTypes["pg/text@1"]["input"] | null;
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly products: {
      readonly brand: CodecTypes["pg/text@1"]["output"];
      readonly category: CodecTypes["pg/text@1"]["output"];
      readonly color: CodecTypes["pg/text@1"]["output"] | null;
      readonly featured: CodecTypes["pg/bool@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly name: CodecTypes["pg/text@1"]["output"];
      readonly price: CodecTypes["pg/float8@1"]["output"];
      readonly processor: CodecTypes["pg/text@1"]["output"] | null;
      readonly ram: CodecTypes["pg/int4@1"]["output"] | null;
      readonly rating: CodecTypes["pg/float8@1"]["output"];
      readonly release_year: CodecTypes["pg/int4@1"]["output"];
      readonly status: CodecTypes["pg/text@1"]["output"];
      readonly stock: CodecTypes["pg/int4@1"]["output"];
      readonly storage: CodecTypes["pg/int4@1"]["output"] | null;
    };
    readonly users: {
      readonly avatar: CodecTypes["pg/text@1"]["output"] | null;
      readonly created_at: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly email: CodecTypes["pg/text@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly name: CodecTypes["pg/text@1"]["output"] | null;
      readonly otp_expiry:
        CodecTypes["pg/timestamptz-string@1"]["output"] | null;
      readonly password: CodecTypes["pg/text@1"]["output"] | null;
      readonly refresh_token: CodecTypes["pg/text@1"]["output"] | null;
      readonly reset_otp: CodecTypes["pg/text@1"]["output"] | null;
      readonly updated_at: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly username: CodecTypes["pg/text@1"]["output"] | null;
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly products: {
      readonly brand: CodecTypes["pg/text@1"]["input"];
      readonly category: CodecTypes["pg/text@1"]["input"];
      readonly color: CodecTypes["pg/text@1"]["input"] | null;
      readonly featured: CodecTypes["pg/bool@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly name: CodecTypes["pg/text@1"]["input"];
      readonly price: CodecTypes["pg/float8@1"]["input"];
      readonly processor: CodecTypes["pg/text@1"]["input"] | null;
      readonly ram: CodecTypes["pg/int4@1"]["input"] | null;
      readonly rating: CodecTypes["pg/float8@1"]["input"];
      readonly release_year: CodecTypes["pg/int4@1"]["input"];
      readonly status: CodecTypes["pg/text@1"]["input"];
      readonly stock: CodecTypes["pg/int4@1"]["input"];
      readonly storage: CodecTypes["pg/int4@1"]["input"] | null;
    };
    readonly users: {
      readonly avatar: CodecTypes["pg/text@1"]["input"] | null;
      readonly created_at: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly email: CodecTypes["pg/text@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly name: CodecTypes["pg/text@1"]["input"] | null;
      readonly otp_expiry:
        CodecTypes["pg/timestamptz-string@1"]["input"] | null;
      readonly password: CodecTypes["pg/text@1"]["input"] | null;
      readonly refresh_token: CodecTypes["pg/text@1"]["input"] | null;
      readonly reset_otp: CodecTypes["pg/text@1"]["input"] | null;
      readonly updated_at: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly username: CodecTypes["pg/text@1"]["input"] | null;
    };
  };
};

export namespace Models {
  export type public_Product = {
    brand: CodecTypes["pg/text@1"]["output"];
    category: CodecTypes["pg/text@1"]["output"];
    color: CodecTypes["pg/text@1"]["output"] | null;
    featured: CodecTypes["pg/bool@1"]["output"];
    id: CodecTypes["pg/text@1"]["output"];
    name: CodecTypes["pg/text@1"]["output"];
    price: CodecTypes["pg/float8@1"]["output"];
    processor: CodecTypes["pg/text@1"]["output"] | null;
    ram: CodecTypes["pg/int4@1"]["output"] | null;
    rating: CodecTypes["pg/float8@1"]["output"];
    releaseYear: CodecTypes["pg/int4@1"]["output"];
    status: CodecTypes["pg/text@1"]["output"];
    stock: CodecTypes["pg/int4@1"]["output"];
    storage: CodecTypes["pg/int4@1"]["output"] | null;
    readonly [RelationKeys]?: never;
  };
  export type public_User = {
    avatar: CodecTypes["pg/text@1"]["output"] | null;
    createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
    email: CodecTypes["pg/text@1"]["output"];
    id: CodecTypes["pg/text@1"]["output"];
    name: CodecTypes["pg/text@1"]["output"] | null;
    otpExpiry: CodecTypes["pg/timestamptz-string@1"]["output"] | null;
    password: CodecTypes["pg/text@1"]["output"] | null;
    refreshToken: CodecTypes["pg/text@1"]["output"] | null;
    resetOtp: CodecTypes["pg/text@1"]["output"] | null;
    updatedAt: CodecTypes["pg/timestamptz-string@1"]["output"];
    username: CodecTypes["pg/text@1"]["output"] | null;
    readonly [RelationKeys]?: never;
  };
}

export declare const models: {
  public: {
    Product: Models.public_Product;
    User: Models.public_User;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: "public";
        readonly kind: "postgres-schema";
        readonly entries: {
          readonly table: {
            readonly products: {
              columns: {
                readonly brand: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly category: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly color: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
                readonly featured: {
                  readonly nativeType: "bool";
                  readonly codecId: "pg/bool@1";
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly price: {
                  readonly nativeType: "float8";
                  readonly codecId: "pg/float8@1";
                  readonly nullable: false;
                };
                readonly processor: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
                readonly ram: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: true;
                };
                readonly rating: {
                  readonly nativeType: "float8";
                  readonly codecId: "pg/float8@1";
                  readonly nullable: false;
                };
                readonly release_year: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly stock: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                };
                readonly storage: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: "products_brand_idx_13825d71";
                  readonly prefix: "products_brand_idx";
                  readonly columns: readonly ["brand"];
                  readonly unique: false;
                },
                {
                  readonly name: "products_category_idx_f2600f8e";
                  readonly prefix: "products_category_idx";
                  readonly columns: readonly ["category"];
                  readonly unique: false;
                },
                {
                  readonly name: "products_price_idx_696ad5eb";
                  readonly prefix: "products_price_idx";
                  readonly columns: readonly ["price"];
                  readonly unique: false;
                },
                {
                  readonly name: "products_rating_idx_fcb0b199";
                  readonly prefix: "products_rating_idx";
                  readonly columns: readonly ["rating"];
                  readonly unique: false;
                },
                {
                  readonly name: "products_release_year_idx_fb38b8a4";
                  readonly prefix: "products_release_year_idx";
                  readonly columns: readonly ["release_year"];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly users: {
              columns: {
                readonly avatar: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
                readonly created_at: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-string@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "function";
                    readonly expression: "now()";
                  };
                };
                readonly email: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
                readonly otp_expiry: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-string@1";
                  readonly nullable: true;
                };
                readonly password: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
                readonly refresh_token: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
                readonly reset_otp: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
                readonly updated_at: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-string@1";
                  readonly nullable: false;
                };
                readonly username: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [
                { readonly columns: readonly ["email"] },
                { readonly columns: readonly ["username"] },
              ];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  "roots" | "domain"
> & {
  readonly target: "postgres";
  readonly targetFamily: "sql";
  readonly roots: {
    readonly products: {
      readonly namespace: "public" & NamespaceId;
      readonly model: "Product";
    };
    readonly users: {
      readonly namespace: "public" & NamespaceId;
      readonly model: "User";
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Product: {
            readonly fields: {
              readonly brand: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly category: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly color: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly featured: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/bool@1";
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly price: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/float8@1";
                };
              };
              readonly processor: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly ram: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly rating: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/float8@1";
                };
              };
              readonly releaseYear: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly stock: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly storage: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: "products";
              readonly namespaceId: "public";
              readonly fields: {
                readonly brand: { readonly column: "brand" };
                readonly category: { readonly column: "category" };
                readonly color: { readonly column: "color" };
                readonly featured: { readonly column: "featured" };
                readonly id: { readonly column: "id" };
                readonly name: { readonly column: "name" };
                readonly price: { readonly column: "price" };
                readonly processor: { readonly column: "processor" };
                readonly ram: { readonly column: "ram" };
                readonly rating: { readonly column: "rating" };
                readonly releaseYear: { readonly column: "release_year" };
                readonly status: { readonly column: "status" };
                readonly stock: { readonly column: "stock" };
                readonly storage: { readonly column: "storage" };
              };
            };
          };
          readonly User: {
            readonly fields: {
              readonly avatar: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-string@1";
                };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly name: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly otpExpiry: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-string@1";
                };
              };
              readonly password: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly refreshToken: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly resetOtp: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-string@1";
                };
              };
              readonly username: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: "users";
              readonly namespaceId: "public";
              readonly fields: {
                readonly avatar: { readonly column: "avatar" };
                readonly createdAt: { readonly column: "created_at" };
                readonly email: { readonly column: "email" };
                readonly id: { readonly column: "id" };
                readonly name: { readonly column: "name" };
                readonly otpExpiry: { readonly column: "otp_expiry" };
                readonly password: { readonly column: "password" };
                readonly refreshToken: { readonly column: "refresh_token" };
                readonly resetOtp: { readonly column: "reset_otp" };
                readonly updatedAt: { readonly column: "updated_at" };
                readonly username: { readonly column: "username" };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly insertOnConflictSkip: true;
      readonly insertOnConflictWithoutTarget: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly onCreate: {
            readonly id: "uuidv4";
            readonly kind: "generator";
          };
          readonly ref: {
            readonly entry: "products";
            readonly field: "id";
            readonly namespace: "public";
          };
        },
        {
          readonly onCreate: {
            readonly id: "uuidv4";
            readonly kind: "generator";
          };
          readonly ref: {
            readonly entry: "users";
            readonly field: "id";
            readonly namespace: "public";
          };
        },
        {
          readonly onCreate: {
            readonly id: "timestampNow";
            readonly kind: "generator";
          };
          readonly onUpdate: {
            readonly id: "timestampNow";
            readonly kind: "generator";
          };
          readonly ref: {
            readonly entry: "users";
            readonly field: "updated_at";
            readonly namespace: "public";
          };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract["storage"]["namespaces"];
